### PR TITLE
fixed a problem where pressure plates would be reset if the agent and…

### PR DESCRIPTION
**Pull request by WilliamHarmonMS**
… player shared an index

Resolves https://github.com/code-dot-org/craft/issues/206.

### CODE REVIEW

**Comment by WilliamHarmonMS** [comment]
Well we don't want -any- entity to trigger a pressure plate. Only the player or Agent. If the player is moving off a pressure plate the only thing he needs to be concerned with is if the Agent is still there? I mean you're right it's not referencing the plate exactly, but that is the only case that should leave the pressure plate triggered after moving off it.

Though we could still say "getblockat(position) === pressure plate && agent.position === position"

or something like that?

**Comment by Hamms** [comment]
Let's then add an Entity method `canTriggerPressurePlate`, and check for entities that fulfill that requirement

**Comment by WilliamHarmonMS** [comment]
@Hamms PTAL 👍

**Comment by joshlory** [comment]
Test coverage?

**Comment by WilliamHarmonMS** [comment]
Given that this was approved, I'm going to merge it through and will make another PR for some unit tests 👍 

Just want to make sure it's included for tomorrows tests if possible

**Pull request merged**
