### PR TITLE
Bubble column should be transparent for FoW calculation

### PR DESCRIPTION
**Pull request by joshlory**
Before:

After:

### CODE REVIEW

**Comment by Hamms** [comment]
I'm not seeing the differences here; can you explain a bit?

**Comment by joshlory** [comment]
Only the center area is lit before (from sea lanterns).  After, the magma also is lit.

**Comment by joshlory** [comment]
Take a look at the lightness of the bottom left and bottom right corners!  (of the grey stone blocks, near the magma bubbles)

**Comment by Hamms** [comment]
Ooooh, there it is! I had been looking at the floor-level blocks more than at the play-level blocks

**Pull request merged**
