### PR TITLE
agent can now move through Steve

### PR DESCRIPTION
**Pull request by WilliamHarmonMS**
Agent needs to not be blocked by steve, just like steve isn't blocked by the agent.

Resolves https://github.com/code-dot-org/craft/issues/205.

### CODE REVIEW

**Comment by WilliamHarmonMS** [comment]
Well, canMoveThrough() for Agent is always true. But that's not the case for all entities. Cows and sheeps and stuff would not move through the Agent. In minecraft they move around the Agent (though they don't prevent the Agent from moving, he would likely just "bump" them out of the way, which is something that we could do at some point but not something I'm super worried about). The only thing that can actively move through the Agent with no repercussions is the player.

like wise, the Agent moving through the player is without repercussion, but as I said he bumps other entities aside a bit (he moves through regardless, but they make a token effort to get out of the way).

I'm a bit wary about using "targetEntity.canMoveThrough() || this.canMoveThrough()" as a part of the check because of how systemic that permission would be.

**Comment by Hamms** [comment]
Ahh, that makes sense; I didn't realize that the agents move through property was unique to the player. This means that we'll likely need to update the existing move through logic, since right now I think anything will be able to move through it.

This LGTM for now

**Comment by joshlory** [comment]
Until non-player entities have logic to move around the Agent, should we let them move through the Agent?  What is the downside?

**Comment by WilliamHarmonMS** [comment]
>"Until non-player entities have logic to move around the Agent"

Do the other entities not do A*? I swear I saw an A* logic somewhere.

**Pull request merged**
